server:
 port: 2001
spring:
 application:
    name: configServer
 cloud: 
  config: 
   server: 
    git:
     uri: https://github.com/wind3/vigalyn-cloud-config
     searchPaths: appConfig
eureka: 
  instance:
    hostname: localhost
#    appname: configServer
    port: 1002
  client:
    service-url: 
     defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

      
    